### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ghost**
Fix Mozilla Firefox icons

### CODE REVIEW

**Comment by Elbullazul** [comment]
Could you submit a new pull request but with the pre-quantum icon?

**Comment by ghost** [comment]
Hi, 
This is the quantum icon if i'm not mistake i just check it on google and it is...
Or do you mean the bleu new developers beta icon of quantum?

**Comment by Elbullazul** [comment]
I meant the old one:
img

**Comment by Elbullazul** [comment]
It'll look more like XP since quantum won't run on it

**Comment by ghost** [comment]
Ok i fix it thanks

**Comment by dominichayesferen** [comment]
@Elbullazul Australis Firefox's Logo would fit fine though too... (Australis was in XP Compatible Firefox)

**Pull request closed without merging**
